from __future__ import annotations

DEFAULT_CREDENTIAL_PROVIDER_ALIAS = "OpenAI"
DEFAULT_CREDENTIAL_SERVICE_TYPE_NAME = "LLM"
DEFAULT_CREDENTIAL_SERVICE_ID = 30
DEFAULT_CREDENTIAL_PREFETCH_HINTS: tuple[tuple[str, str], ...] = (
    (DEFAULT_CREDENTIAL_PROVIDER_ALIAS, DEFAULT_CREDENTIAL_SERVICE_TYPE_NAME),
)
