"""Build an AWX flow directory from the canonical repository source."""

from __future__ import annotations

import argparse
import shutil
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT = REPO_ROOT / "dist" / "awx-flow"

CANONICAL_FILES = [
    "app.py",
    "config.py",
    "seed.py",
    "README.md",
    ".env.example",
]
CANONICAL_DIRS = [
    "src",
    "static",
    "templates",
]
AWX_FILES = {
    "awx/run-application.sh": "run-application.sh",
    "awx/awx-bootstrap.json": "awx-bootstrap.json",
    "awx/pyproject.toml": "pyproject.toml",
    "awx/README.md": "AWX_README.md",
}
IGNORE_PATTERNS = (
    "__pycache__",
    "*.pyc",
    "*.pyo",
    ".pytest_cache",
    ".mypy_cache",
    "*.db",
    "*.sqlite",
    "*.sqlite3",
    "*.log",
)


def build_awx_flow(output: Path, *, clean: bool = False, include_tests: bool = False) -> None:
    output = output.resolve()
    _assert_safe_output(output)

    if clean and output.exists():
        shutil.rmtree(output)
    output.mkdir(parents=True, exist_ok=True)

    for source_name in CANONICAL_FILES:
        source = REPO_ROOT / source_name
        if source.exists():
            shutil.copy2(source, output / source.name)

    dirs = list(CANONICAL_DIRS)
    if include_tests:
        dirs.append("tests")

    for dirname in dirs:
        source = REPO_ROOT / dirname
        target = output / dirname
        if target.exists():
            shutil.rmtree(target)
        shutil.copytree(source, target, ignore=shutil.ignore_patterns(*IGNORE_PATTERNS))

    for source_name, target_name in AWX_FILES.items():
        shutil.copy2(REPO_ROOT / source_name, output / target_name)

    _write_build_marker(output)


def _assert_safe_output(output: Path) -> None:
    try:
        output.relative_to(REPO_ROOT)
    except ValueError as exc:
        raise ValueError(f"Output must be inside the repository: {output}") from exc

    if output == REPO_ROOT:
        raise ValueError("Output must not be the repository root.")


def _write_build_marker(output: Path) -> None:
    marker = output / ".awx-flow-build"
    marker.write_text(
        "Generated by scripts/build_awx_flow.py from repository canonical source.\n",
        encoding="utf-8",
    )


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output",
        default=str(DEFAULT_OUTPUT),
        help="Output directory for the generated AWX flow.",
    )
    parser.add_argument(
        "--clean",
        action="store_true",
        help="Delete the output directory before rebuilding it.",
    )
    parser.add_argument(
        "--include-tests",
        action="store_true",
        help="Copy tests into the generated flow for validation builds.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    output = Path(args.output)
    build_awx_flow(output, clean=args.clean, include_tests=args.include_tests)
    print(f"AWX flow generated at: {output.resolve()}")


if __name__ == "__main__":
    main()

